[local]
localhost ansible_connection=local ansible_python_interpreter=/home/cherepashka/ansible-venv/bin/python

[containers]
target1 ansible_host=127.0.0.1 ansible_port=2222 ansible_user=root ansible_password=root ansible_ssh_common_args='-o StrictHostKeyChecking=no'

[web]
web-server ansible_host=192.168.1.10 ansible_user=ubuntu

[db]
db-server ansible_host=192.168.1.20 ansible_user=ubuntu